_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
data:
    value: custom
model:
    value: TimesNet
n_trials:
    value: 50
pred_len:
    value: 48
task:
    value: long_term_forecast
