_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 1
                - 2
                - 13
                - 16
                - 23
                - 55
                - 61
                - 62
            "4": 3.8.20
            "5": 0.19.11
            "8":
                - 5
            "10":
                - 20
            "12": 0.19.11
            "13": linux-x86_64
d_layers:
    value: 2
data:
    value: custom
e_layers:
    value: 1
factor:
    value: 2
freq:
    value: h
model:
    value: TimesNet
pred_len:
    value: 48
task:
    value: long_term_forecast
top_k:
    value: 3
trial_number:
    value: 60
