_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.11
            "8":
                - 5
            "10":
                - 20
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 8
d_ff_mult:
    value: 8
d_layers:
    value: 3
d_model:
    value: 128
data:
    value: custom
dropout:
    value: 0.456748420304309
e_layers:
    value: 1
factor:
    value: 2
lr:
    value: 0.00014641711409901526
model:
    value: TimesNet
n_heads:
    value: 2
pred_len:
    value: 48
task:
    value: long_term_forecast
top_k:
    value: 2
trial_number:
    value: 44
